version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.0
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.20.0
    - 4.21.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@types/eslint"
    versions:
    - 7.2.6
    - 7.2.7
    - 7.2.8
    - 7.2.9
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.0
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.10
    - 9.0.6
    - 9.0.7
    - 9.0.8
    - 9.0.9
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: got
    versions:
    - 11.8.1
    - 11.8.2
  - dependency-name: execa
    versions:
    - 5.0.0
  - dependency-name: node-gyp
    versions:
    - 7.1.2
