version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    registries: "*"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/"
    registries: "*"
    schedule:
      interval: "monthly"