language: node_js

dist: xenial

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      addons: &gcc7
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env:
        - CXX_COMPILER='g++-7'
        - C_COMPILER='gcc-7'

    - os: osx
      env:
        - MACOSX_DEPLOYMENT_TARGET=10.9

branches:
  only:
    - develop
    - /^v.*$/

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

node_js:
  - '10.15.3'

before_install:
  - eval "${MATRIX_EVAL}"

  - git clone https://github.com/greenheartgames/greenworks greenworks

#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install p7zip; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y p7zip-full; fi

  - 7z x sdk.zip -p$ZIP_PASSWORD
  - mv sdk greenworks/deps/steamworks_sdk
#  - npm i -g npx
  - npm install

script:
  - echo $CXX_COMPILER
  - echo $C_COMPILER
  - echo $CC
  - echo $CXX
  - echo $MACOSX_DEPLOYMENT_TARGET
  - echo $TRAVIS_TAG

#  - mkdir prebuilds
  - cd greenworks
  - npm install
  - cd ..
  - node index.js
