# https://github.com/prebuild/prebuild
# https://github.com/greenheartgames/greenworks/blob/master/docs/build-instructions-nwjs.md
# https://github.com/greenheartgames/greenworks/blob/master/docs/build-instructions-electron.md

language: node_js

dist: trusty

matrix:
  include:
    - os: linux
      compiler: clang
      addons: &clang38
        apt:
          packages:
            - clang-3.8
            - cmake3
            - gfortran
            - swig
      env:
        - CXX_COMPILER='clang++-3.8'
        - C_COMPILER='clang-3.8'

    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake3
            - g++-7
            - gcc-7
            - gfortran-7
            - swig
      env:
        - CXX_COMPILER='g++-7'
        - C_COMPILER='gcc-7'

    - os: osx
      compiler: clang
      osx_image: xcode8
      env:
        - CXX_COMPILER='clang++'
        - C_COMPILER='clang'      
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: osx    
      compiler: gcc
      osx_image: xcode8
      env:
        - CXX_COMPILER='g++'
        - C_COMPILER='gcc'      
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

branches:
  only:
    - master
    - develop
    - test

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

node_js:
  - '10.15.2'

before_install:
  - git clone https://github.com/greenheartgames/greenworks greenworks 

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval "${MATRIX_EVAL}"; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install p7zip; fi
  -
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y p7zip-full; fi

  - 7z x sdk.zip -p$ZIP_PASSWORD
  - mv sdk greenworks/deps/steamworks_sdk
  - ls greenworks
  - ls greenworks/deps
  - ls greenworks/deps/steamworks_sdk
  - npm i -g npx
  - npm install

script:
  - export CXX=g++-4.8
  - export MACOSX_DEPLOYMENT_TARGET=10.7

  - cd greenworks
  - npm install
  - mkdir prebuilds
  - echo $BONJOUR
  - npx prebuild --all -u $GH_TOKEN --verbose
