# https://github.com/prebuild/prebuild
# https://github.com/greenheartgames/greenworks/blob/master/docs/build-instructions-nwjs.md
# https://github.com/greenheartgames/greenworks/blob/master/docs/build-instructions-electron.md

language: node_js

dist: xenial

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      addons: &gcc7
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake3
            - g++-7
            - gcc-7
            - gfortran-7
            - swig
      env:
        - CXX_COMPILER='g++-7'
        - C_COMPILER='gcc-7'

    - os: osx
      compiler: clang
      osx_image: xcode10
      env:
        - CXX_COMPILER='clang++'
        - C_COMPILER='clang'
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9 && MACOSX_DEPLOYMENT_TARGET=10.7"

    - os: osx
      compiler: gcc
      osx_image: xcode10
      env:
        - CXX_COMPILER='g++'
        - C_COMPILER='gcc'
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9 && MACOSX_DEPLOYMENT_TARGET=10.7"

branches:
  only:
    - master
    - develop
    - /^v.*$/

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

node_js:
  - '10.15.2'

before_install:
  - eval "${MATRIX_EVAL}"

  - git clone https://github.com/greenheartgames/greenworks greenworks

#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install p7zip; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y p7zip-full; fi

  - 7z x sdk.zip -p$ZIP_PASSWORD
  - mv sdk greenworks/deps/steamworks_sdk
  - ls greenworks
  - ls greenworks/deps
  - ls greenworks/deps/steamworks_sdk
  - npm i -g npx
  - npm install

script:
  - echo $CXX_COMPILER
  - echo $C_COMPILER
  - echo $CC
  - echo $CXX
  - echo $MACOSX_DEPLOYMENT_TARGET

  - mkdir prebuilds
  - cd greenworks
  - npm install
  - mkdir prebuilds
  # - npx prebuild --all
  # - mv prebuilds ../prebuilds
  - cd ..
  - node index.js
  - cp greenworks/prebuilds/** prebuilds/
  - npx prebuild --upload-all $GH_TOKEN
