language: node_js

matrix:
  include:
    -
      os: linux
      dist: trusty
      compiler: gcc
      addons: &gcc7
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
            - libc6-dev-i386
            - g++-multilib
      env:
        - CXX_COMPILER='g++-7'
        - C_COMPILER='gcc-7'

    -
      os: osx
      compiler: gcc
      addons: &gcc7
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env:
        - CXX_COMPILER='g++-7'
        - C_COMPILER='gcc-7'
        - MACOSX_DEPLOYMENT_TARGET=10.9

    -
      os: windows
      env: YARN_GPG=no

branches:
  only:
    - master
    - develop
    - v2

notifications:
  email: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

node_js: 10.15.3

before_install:
  - git clone https://github.com/greenheartgames/greenworks greenworks

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install p7zip; fi

  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y p7zip-full; fi

  - 7z x sdk.zip -p$ZIP_PASSWORD
  - mv sdk greenworks/deps/steamworks_sdk
  - npm install

script:
  - echo $CXX_COMPILER
  - echo $C_COMPILER
  - echo $CC
  - echo $CXX
  - echo $MACOSX_DEPLOYMENT_TARGET
  - echo $TRAVIS_TAG

  - npx tsc
  - cd greenworks
  - npm install
  - cd ..
  - node dist/index.js

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Runner"
  - git config --local user.email "runner@armaldio.xyz"
  # - export TRAVIS_TAG=TEST
  # - TRAVIS_TAG=$(node getRelease.js) && git tag $TRAVIS_TAG
  - TRAVIS_TAG=$(node getRelease.js)

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: artifacts/**/*
  skip_cleanup: true
  draft: false
  overwrite: true
  prerelease: false
  on:
    branch: master
