environment:
  matrix:
    - nodejs_version: "10.0"

platform:
  - x64

os: Visual Studio 2017

build: off

branches:
  only:
    - master
    - develop
    - /^v.*$/

# init:
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - git clone https://github.com/greenheartgames/greenworks greenworks

  - echo $env:ZIP_PASSWORD
  - echo %ZIP_PASSWORD%
  - 7z x sdk.zip -p$env:ZIP_PASSWORD
  - mv sdk greenworks/deps/steamworks_sdk
  - ls greenworks
  - ls greenworks/deps
  - ls greenworks/deps/steamworks_sdk
  - npm i -g npx
  - npm install

  - mkdir prebuilds
  - cd greenworks
  - npm install
  - mkdir prebuilds
  - cd ..
  - node index.js
  - cp greenworks/prebuilds/** prebuilds/
  - npx prebuild --upload-all $env:GH_TOKEN
