environment:
  matrix:
    - nodejs_version: "10"

platform:
  - x64

os: Visual Studio 2015

build: off

branches:
  only:
    - develop
    - /^v.*$/

# init:
install:
  - ps: Install-Product node $env:nodejs_version
  - git clone https://github.com/greenheartgames/greenworks greenworks
  - 7z x sdk.zip -p"%ZIP_PASSWORD%"
  - mv sdk greenworks/deps/steamworks_sdk
  - npm install
  - cd greenworks
  - npm install
  - cd ..
  - node index.js
