name: Build
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [ '10.15.3' ] # , '12.16.2', '13.12.0' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checout Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      
      - run: git clone https://github.com/greenheartgames/greenworks greenworks

      # Install dep
      - if: matrix.os == 'macos-latest'
        run: brew install p7zip

      # Extract
      - run: 7z x sdk.zip -p$ZIP_PASSWORD
        env:
          ZIP_PASSWORD: ${{ secrets.ZIP_PASSWORD }}

      - run: mv sdk greenworks/deps/steamworks_sdk
      - run: npm install

      - run: echo $CXX_COMPILER
      - run: echo $C_COMPILER
      - run: echo $CC
      - run: echo $CXX
      - run: echo $MACOSX_DEPLOYMENT_TARGET
      - run: echo $TRAVIS_TAG

      - run: cd greenworks
      - run: npm install
      - run: cd ..
      - run: npx tsc
      - run: node dist/index.js