name: Build
on: [push]

jobs:
  make_matrix:
    name: Generate Matrix
    runs-on: ubuntu-latest
    outputs:
      # matrix: ${{ steps.set-matrix.outputs.matrix }}
      matrix2: ${{ steps.set-matrix2.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.0"

      - run: npm install
      - run: npx tsc
      - run: node ./dist/makeMatrix.js
      - run: ls
      # - id: set-matrix
      #   run: |
      #     body=$(node ./dist/makeMatrix.js)
      #     body="${content//'%'/'%25'}"
      #     body="${content//$'\n'/'%0A'}"
      #     body="${content//$'\r'/'%0D'}"
      #     echo "::set-output name=matrix::$body"
      - id: set-matrix2
        run: |
          JSON=$(cat ./matrix.json)
          echo $JSON
          echo "::set-output name=matrix::$JSON"

  build:
    name: Build
    needs: make_matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [2.7]
        os: [macos-latest, ubuntu-latest] # windows-latest,
        # node_config: ${{fromJson(needs.make_matrix.outputs.matrix)}}
    steps:

      # - run: echo ${{ needs.make_matrix.outputs.matrix }}
      - run: echo ${{ needs.make_matrix.outputs.matrix2 }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.19.0"

      - run: git clone https://github.com/greenheartgames/greenworks greenworks

      # Install dep
      - if: matrix.os == 'macos-latest'
        run: brew install p7zip

      # - if: matrix.os == 'ubuntu-latest'
      #   run: pyenv install 2.7.14

      - run: python --version

      # Extract
      - run: 7z x sdk.zip -P${{ secrets.ZIP_PASSWORD }}

      - run: mv sdk greenworks/deps/steamworks_sdk
      - run: npm install

      - run: echo $CXX_COMPILER
      - run: echo $C_COMPILER
      - run: echo $CC
      - run: echo $CXX
      - run: echo $MACOSX_DEPLOYMENT_TARGET
      - run: echo $TRAVIS_TAG

      - run: |
          cd greenworks
          npm install

      - run: npx tsc
      - run: node dist/index.js
